### ISSUE TITLE
CLI should be separate module

### ISSUE THREAD

**Issue by simontabor** [ideal-postcodes/ideal-postcodes-node#6]
Most of the dependencies for this module are related to the CLI. It'd be nicer to have the CLI split off as a separate module (especially the logstream parts) so these bloat dependencies can be removed.

**Comment by cblanc** [comment]
I think you're right, will got it done some time this week

Thanks

**Comment by simontabor** [comment]
awesome, thank you!

**Comment by cblanc** [comment]
Split off the CLI and release a new major version for this module 1.0.0
